from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
DATABASE_PATH = DATA_DIR / "traductor_lsc.db"
DATASET_PATH = DATA_DIR / "senas.csv"
LEGACY_DATASET_PATH = DATA_DIR / "señas.csv"
MODEL_PATH = MODELS_DIR / "modelo_lsc.pkl"
ETIQUETAS_SIN_SENA = {"sin_sena", "reposo", "ninguna", "no_sena", "transicion"}
REQUISITOS_SENAS = {
    "saludos": {
        "min_manos": 2,
        "min_frames_manos": 14,
    },
}
LANDMARKS_POR_MANO = 21 * 3
MAX_MANOS = 2
REFERENCIAS_CUERPO = 5
COORDENADAS_POR_REFERENCIA = 3
ZONAS_REFERENCIA_POR_MANO = REFERENCIAS_CUERPO
LADOS_CUERPO_POR_MANO = 3
ALTURAS_CUERPO_POR_MANO = 3
CARACTERISTICAS_CONTEXTO_POR_MANO = (
    1
    + 3
    + (REFERENCIAS_CUERPO * 4)
    + ZONAS_REFERENCIA_POR_MANO
    + LADOS_CUERPO_POR_MANO
    + ALTURAS_CUERPO_POR_MANO
)
CARACTERISTICAS_REFERENCIAS_CUERPO = (REFERENCIAS_CUERPO * COORDENADAS_POR_REFERENCIA) + 1
ENTRADA_MODELO = (
    LANDMARKS_POR_MANO * MAX_MANOS
    + CARACTERISTICAS_CONTEXTO_POR_MANO * MAX_MANOS
    + CARACTERISTICAS_REFERENCIAS_CUERPO
)
FRAMES_SECUENCIA = 20
MIN_FRAMES_MANO_CAPTURA = 14
ENTRADA_MODELO_TEMPORAL = ENTRADA_MODELO * 3
