from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = PROJECT_ROOT / "data"
MODELS_DIR = PROJECT_ROOT / "models"
DATASET_PATH = DATA_DIR / "senas.csv"
LEGACY_DATASET_PATH = DATA_DIR / "señas.csv"
MODEL_PATH = MODELS_DIR / "modelo_lsc.pkl"
ETIQUETAS_SIN_SENA = {"sin_sena", "reposo", "ninguna", "no_sena", "transicion"}
LANDMARKS_POR_MANO = 21 * 3
MAX_MANOS = 2
REFERENCIAS_CUERPO = 5
COORDENADAS_POR_REFERENCIA = 3
CARACTERISTICAS_CONTEXTO_POR_MANO = 1 + 3 + (REFERENCIAS_CUERPO * 4)
CARACTERISTICAS_REFERENCIAS_CUERPO = (REFERENCIAS_CUERPO * COORDENADAS_POR_REFERENCIA) + 1
ENTRADA_MODELO = (
    LANDMARKS_POR_MANO * MAX_MANOS
    + CARACTERISTICAS_CONTEXTO_POR_MANO * MAX_MANOS
    + CARACTERISTICAS_REFERENCIAS_CUERPO
)
FRAMES_SECUENCIA = 12
ENTRADA_MODELO_TEMPORAL = ENTRADA_MODELO * 3
